// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 16.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyAnalyzer.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class SingleLoopTemplate : SingleLoopTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("namespace ");
            
            #line 6 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeSymbol.ContainingNamespace.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    ");
            
            #line 8 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeSymbol.IsStatic ? "static " : ""));
            
            #line default
            #line hidden
            this.Write("partial ");
            
            #line 8 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeSymbol.IsValueType ? "struct " : "class "));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 8 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeSymbol.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        [global::Unity.Burst.BurstCompile]\r\n        public unsafe partia" +
                    "l struct Job : global::Unity.Jobs.IJob\r\n        {\r\n");
            
            #line 13 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Outers.Length; ++index) {
    var item = Outers[index]; 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 15 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("[global::Unity.Collections.ReadOnly] ");
            
            #line 15 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("public global::Unity.Collections.NativeArray<");
            
            #line 15 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write(".Eight> Outer");
            
            #line 15 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 16 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Others.Length; ++index) {
    var item = Others[index]; 
    if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 20 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write(" Other");
            
            #line 20 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            public global::Unity.Collections.NativeArray<");
            
            #line 22 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write("> Other");
            
            #line 22 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 23 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Tables.Length; ++index) {
    var item = Tables[index]; 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 27 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("[global::Unity.Collections.ReadOnly] ");
            
            #line 27 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("public global::Unity.Collections.NativeArray<");
            
            #line 27 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write("> Table");
            
            #line 27 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            public void Execute()\r\n            {\r\n");
            
            #line 32 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Tables.Length; ++index) {
    var item = Tables[index];
    if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("                var tablePointer");
            
            #line 35 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = global::Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeRe" +
                    "adOnlyPtr(Table");
            
            #line 35 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 36 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                var tablePointer");
            
            #line 37 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = global::Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetUnsafeBu" +
                    "fferPointerWithoutChecks(Table");
            
            #line 37 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 38 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 40 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 if (Fma.HasValue) { var method = Fma.Value; 
            
            #line default
            #line hidden
            this.Write("                if (global::Unity.Burst.Intrinsics.X86.Fma.IsFmaSupported)\r\n     " +
                    "           {\r\n");
            
            #line 43 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Others.Length; ++index) {
    var item = Others[index];
    if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("                    var other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = new global::Unity.Burst.Intrinsics.v256(Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 46 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 47 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    var other");
            
            #line 48 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = Other");
            
            #line 48 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[0];\r\n");
            
            #line 49 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 50 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Outers.Length; ++index) {
    var item = Outers[index]; 
            
            #line default
            #line hidden
            this.Write("                    var outerPointer");
            
            #line 53 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = (byte*)global::Unity.Collections.LowLevel.Unsafe.NativeArrayUnsafeUtility.GetU" +
                    "nsafeBufferPointerWithoutChecks(Outer");
            
            #line 53 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 54 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                    for (\r\n                        var outerIndex = 0;\r\n       " +
                    "                 outerIndex < Outer0.Length;\r\n                        ++outerInd" +
                    "ex");
            
            #line 59 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Outers.Length; ++index) { 
            
            #line default
            #line hidden
            this.Write(",\r\n                        outerPointer");
            
            #line 60 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" += sizeof(");
            
            #line 60 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Outers[index].Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write(".Eight)");
            
            #line 60 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                    )\r\n                    {\r\n");
            
            #line 64 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < method.Outers.Length; ++index) {
    var item = method.Outers[index];
    var fieldIndex = item.GetIndex(Outers[item.Index].Symbol); 
            
            #line default
            #line hidden
            this.Write("                        var outer");
            
            #line 67 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Index));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 67 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(" = global::Unity.Burst.Intrinsics.X86.Avx.mm256_load_ps(outerPointer");
            
            #line 67 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Index));
            
            #line default
            #line hidden
            this.Write(" + (");
            
            #line 67 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldIndex));
            
            #line default
            #line hidden
            this.Write(" << 5));\r\n");
            
            #line 68 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 { 
      var parameter = method.Outers[0]; 
            
            #line default
            #line hidden
            this.Write("                        ");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Symbol.Name));
            
            #line default
            #line hidden
            this.Write("(ref outer");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 1; index < method.Outers.Length; ++index) { parameter = method.Outers[index]; 
            
            #line default
            #line hidden
            this.Write(", ref outer");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } for (var index = 0; index < method.Others.Length; ++index) { parameter = method.Others[index]; 
            
            #line default
            #line hidden
            this.Write(", ref other");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } for (var index = 0; index < method.Tables.Length; ++index) { parameter = method.Tables[index]; 
            
            #line default
            #line hidden
            this.Write(", tablePointer");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(", Table");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(".Length");
            
            #line 71 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 72 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < method.Outers.Length; ++index) {
    var item = method.Outers[index];
    var typeItem = Outers[item.Index];
    if (typeItem.IsReadOnly) { continue; }
    var fieldIndex = item.GetIndex(typeItem.Symbol); 
            
            #line default
            #line hidden
            this.Write("                        global::Unity.Burst.Intrinsics.X86.Avx.mm256_store_ps(out" +
                    "erPointer");
            
            #line 78 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Index));
            
            #line default
            #line hidden
            this.Write(" + (");
            
            #line 78 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fieldIndex));
            
            #line default
            #line hidden
            this.Write(" << 5), outer");
            
            #line 78 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Index));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 78 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 79 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    }\r\n");
            
            #line 81 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Others.Length; ++index) {
    var item = Others[index];
    if (item.IsReadOnly) { continue; } 
            
            #line default
            #line hidden
            this.Write("\r\n                    Other");
            
            #line 85 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[0] = other");
            
            #line 85 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 86 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    return;\r\n                }\r\n\r\n");
            
            #line 90 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 { var method = Ordinal; 
            
            #line default
            #line hidden
            this.Write("                {\r\n");
            
            #line 93 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Others.Length; ++index) {
    var item = Others[index];
    if (item.IsReadOnly) { 
            
            #line default
            #line hidden
            this.Write("                    var other");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = new global::Unity.Mathematics.");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Symbol.ToDisplayString()));
            
            #line default
            #line hidden
            this.Write("4(Other");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(", Other");
            
            #line 96 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 97 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    var other");
            
            #line 98 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = Other");
            
            #line 98 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[0];\r\n");
            
            #line 99 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 100 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n                    for (var outerIndex = 0; outerIndex < Outer0.Length; ++oute" +
                    "rIndex)\r\n                    {\r\n");
            
            #line 104 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Outers.Length; ++index) {
    var item = Outers[index]; 
            
            #line default
            #line hidden
            this.Write("                        var outer");
            
            #line 106 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" = Outer");
            
            #line 106 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[outerIndex];\r\n");
            
            #line 107 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 108 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var cIndex0 = 0; cIndex0 < 2; ++cIndex0) {
      var parameter = method.Outers[0]; 
            
            #line default
            #line hidden
            this.Write("                        ");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Symbol.Name));
            
            #line default
            #line hidden
            this.Write("(ref outer");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(".c");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cIndex0));
            
            #line default
            #line hidden
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 1; index < method.Outers.Length; ++index) { parameter = method.Outers[index]; 
            
            #line default
            #line hidden
            this.Write(", ref outer");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write(".c");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cIndex0));
            
            #line default
            #line hidden
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } for (var index = 0; index < method.Others.Length; ++index) { parameter = method.Others[index]; 
            
            #line default
            #line hidden
            this.Write(", ref other");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } for (var index = 0; index < method.Tables.Length; ++index) { parameter = method.Tables[index]; 
            
            #line default
            #line hidden
            this.Write(", tablePointer");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(", Table");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Index));
            
            #line default
            #line hidden
            this.Write(".Length");
            
            #line 110 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 111 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 112 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Outers.Length; ++index) {
    var item = Outers[index];
    if (item.IsReadOnly) { continue; } 
            
            #line default
            #line hidden
            this.Write("                        Outer");
            
            #line 115 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[outerIndex] = outer");
            
            #line 115 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 116 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    }\r\n");
            
            #line 118 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 for (var index = 0; index < Others.Length; ++index) {
    var item = Others[index];
    if (item.IsReadOnly) { continue; } 
            
            #line default
            #line hidden
            this.Write("\r\n                    Other");
            
            #line 122 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("[0] = other");
            
            #line 122 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 123 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                }\r\n");
            
            #line 125 "C:\Users\conve\source\repos\Unity1Week_P1145141919\Managed\MyAnalyzer\Templates\SingleLoopTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class SingleLoopTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
